name: Inject GitHub Token

on:
  push:
    branches:
      - main  # Change selon ta branche
  workflow_dispatch:

jobs:
  inject-token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du repo
        uses: actions/checkout@v3

      - name: Injecter le token dans token.js
        run: echo "export const GITHUB_TOKEN = '${{ secrets.GITHUB_TOKEN_CANTINA }}';" > token.js

      - name: Commit du token temporaire
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add token.js
          git commit -m "Mise à jour automatique du token"
          git push
